config/routes.rb
Rails.application.routes.draw do
  get 'bookings/show'

  get 'bookings/new'

  get 'bookings/create'

  devise_for :users
  root to: 'pages#home'

  resources :users do
    resources :bookings, :planes
  end

  resources :planes do
    resources :available_days, :reviews, :bookings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_day.rb
class AvailableDay < ApplicationRecord

  validates :date, uniqueness: { scope: :plane_id }
  validates :date, :plane_id, presence: true

  belongs_to :plane
end

app/models/booking.rb
class Booking < ApplicationRecord

  validates :start_date, :end_date, :user_id, :plane_id, presence: true

  belongs_to :user
  belongs_to :plane
end

app/models/plane.rb
class Plane < ApplicationRecord

  validates :description, :model, :photo, :user, :capacity, :price, presence: true
  scope :query, lambda { |query|
    where('description || model iLIKE ?', "%#{query}%")
  }
  has_many :bookings
  has_many :reviews
  has_many :available_days
  belongs_to :user

  # geocoded_by :address
  # after_validation :geocode, if: :address_changed?


   mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord

  validates :content, :stars, :user_id, :plane_id, presence: true

  belongs_to :user
  belongs_to :plane
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: true
  validates :first_name, :last_name, :email, :phone, presence: true

  has_many :bookings
  has_many :reviews
  has_many :planes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :authenticate_user!

  def show
  end

  def new
    @booking = Booking.new
    @plane = Plane.find(params[:id])
  end

  def plane
    Plane.where(id: booking.plane_id).first
  end

  def create
    booking = Booking.new(booking_params)
    booking.user_id = current_user.id
    booking.plane_id = params[:plane_id]
    booking.save!
  end

  private

  def booking_params
  params.require(:booking).permit(:start_date, :end_date, :user_id, :plane_id )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :authenticate_user!, except: [ :home ]
  def home
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]

before_action :find_plane, only: [:show]
  def index
  if params[:query] == "planes"
    return @planes = Plane.all
  elsif params[:query] && params[:query].length>0
    @planes = Plane.query(params[:query])
  else
    @planes = Plane.all
  end
  end

  def new
    @plane = Plane.new
  end

  def create
    @plane = Plane.new(plane_params)
    @plane.user = current_user
    @plane.save

    redirect_to planes_path
  end



  def show
    @booking = Booking.new
  end
end


private

def find_plane
    @plane = Plane.find(params[:id])
end

def plane_params
  params.require(:plane).permit(:model, :description, :photo, :user, :capacity, :price, :photo_cache )
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, only: [:show]

  def show
    @bookings = Booking.all.where(user_id: params[:id])
    @planes = Plane.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.save
    user_find = User.find_by email: "#{user.email}"
    redirect_to user_path(user_find.id)
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Co-Pilot</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>


<!--   <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->

<%= render 'layouts/shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

<%= render 'layouts/shared/footer' %>
</body>
  </html>

app/views/layouts/shared/_footer.html.erb
<div id="container">

   <div id="footer"><title>Footer With Address And Phones</title>

  <link rel="stylesheet" href="css/demo.css">
  <link rel="stylesheet" href="css/footer-distributed-with-address-and-phones.css">

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

</head>

  <body>


    <!-- The content of your page would go here. -->

    <footer class="footer-distributed">

      <div class="footer-left">

        <h3>Co-<span>pilot</span></h3>

        <p class="footer-links">
          <a href="/">Home</a>
          ·
          <a href="/planes">Planes</a>
          ·
          <a href="#">Pricing</a>
          ·
          <a href="#">Story</a>
          ·
          <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">Co-pilot &copy; 2016</p>
      </div>

      <div class="footer-center">

        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>36 rue de l'avion</span> Marseille, France</p>
        </div>

        <div>
          <i class="fa fa-phone"></i>
          <p>+1 555 123456</p>
        </div>

        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="mailto:support@company.com">support@company.com</a></p>
        </div>

      </div>

      <div class="footer-right">

        <p class="footer-company-about">
          <span>About Co-Pilot</span>
          Co-Pilot connect humans with planes. We decided that a private jet should be affordable for everyone.
        </p>

        <div class="footer-icons">

          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-github"></i></a>

        </div>

      </div>

    </footer>

  </body>

</html>
</div>

</div>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "plane.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="/planes" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something" name="query" id='query'>
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="homepage-hero-module">
    <div class="video-container">
        <div class="filter"></div>
        <video autoplay loop class="fillWidth">
            <source src="/assets/In-The-Clouds.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="/assets/In-The-Clouds.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video>
        <div class="poster hidden">
            <img src="/assets/In-The-Clouds.jpg" alt="">
        </div>
        <div class="title-container">
          <h1>Welcome aboard</h1>
          <h3>Rent planes and their pilotes to travel faster and safer to your destination</h3>
          <a class="btn btn-primary btn-large" href="#">Your planes</a>
        </div>
    </div>
</div>


<div class="head-planes">
  <h2>What will be your ride today ?</h2>

  <p>See the planes at your disposal.</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <img class="card-user avatar" src="user.jpg">
  <a class="card-link" href="#" ></a>
</div>

    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <img class="card-user avatar" src="user.jpg">
  <a class="card-link" href="#" ></a>
</div>

    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <img class="card-user avatar" src="user.jpg">
  <a class="card-link" href="#" ></a>
</div>

    </div>
  </div>
</div>

app/views/planes/_plane_card.html.erb
<div class="col-xs-12 col-sm-4">
  <a href="#">
    <div class="card plane-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( <%=plane.photo.to_s%>);">
      <h2><%= plane.model %></h2>
      <div class="card-description">
        <div class="first"><%= plane.description%></div>
        <div class="last">... read more</div>
      </div>
      <% %>
    </div>
  </a>
</div>

app/views/planes/index.html.erb
<h1>HERE IS A LIST OF ALL PLANES!</h1>


<section id="planes-index"></section>




<div class="container">
  <div class="row">
  <% @planes.each do |plane| %>
   <%= render partial: "plane_card", locals: {plane: plane} %>
  <% end %>
   </div>
</div>



<%= link_to "Add a new plane", new_plane_path, :class => "btn btn-default" %>

app/views/planes/new.html.erb
<%= simple_form_for(@plane) do |f| %>
  <%= f.input :model %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :price %>
  <%= f.input :capacity %>


  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/planes/show.html.erb
<section id="plane-show">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <div class="column-left">
          <div class="imagery">
            <%= cl_image_tag @plane.photo, height: 470, width: 470, crop: :fill %>
          </div>
          <h2>Book this plane</h2>

          <%= form_for [@plane, @booking] do |f| %>
          <%= f.label :start_date %>
          <%= f.date_select :start_date %><br>
          <%= f.label :end_date %>
          <%= f.date_select :end_date %><br>
          <%= f.submit "Book this plane", :class => 'btn btn-primary btn-large' %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="column-right">
          <h2> <%= @plane.model %> </h2>
          <p> <%= @plane.description %> </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<h2>Sign Up</h2>
  <%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<center><h2><%= @user.first_name %> <%= @user.last_name %></h2></center>
<ul>
<ul class="list-group ">
  <li class="list-group-item"><b>Addres:</b> <%= @user.address %></li>
  <li class="list-group-item"><b>Email:</b> <%= @user.email %></li>
  <li class="list-group-item"><b>Phone number:</b> <%= @user.phone %></li>
</ul>


<center><h2>Bookings</h2></center>
<% @bookings.each do |booking| %>
<ul class="list-group ">
  <li class="list-group-item"><b>Start date:</b> <%= booking.start_date %></li>
  <li class="list-group-item"><b>End date:</b> <%= booking.end_date %></li>
  <li class="list-group-item"><b>Plane:</b> <%= booking.plane.model %></li>
</ul>
<% end %>

<center><h2>Your planes</h2></center>
<% @planes.each do |plane| %>
<% if plane.user_id == @user.id %>
<ul class="list-group ">
  <li class="list-group-item"><b>Model:</b><%=link_to "#{plane.model}", plane_path(plane) %></li>
  <li class="list-group-item"><b>Description:</b> <%= plane.description %></li>
  <li class="list-group-item"><b>Capacity:</b> <%= plane.capacity %></li>
</ul>
<% end %>
<% end %>



<p><%=link_to"Go Home", root_path %> <%=link_to"Add a Plane", new_plane_path %></p>